import { prisma } from "../../db/prisma";
import { AppError, notFound } from "../../lib/errors";
import { getDefaultBrandProfile } from "../brand/brandProfileService";
import { runInstagramAgent } from "../agents/instagramAgent";
import { runLinkedInAgent } from "../agents/linkedinAgent";
import { reviewDraftWithSupervisor } from "../agents/supervisorAgent";
import { createNotification } from "../notifications/notificationService";
import { notifyTelegramDraftReady } from "../telegram/telegramApprovalService";
import { createDraftVersion } from "./draftVersionService";

const db = prisma as any;

export async function regenerateDraft(params: {
  draftId: string;
  userId: string | null;
  comment?: string;
  action: "request_revision" | "regenerate";
}) {
  const draft = await db.draft.findUnique({
    where: { id: params.draftId },
    include: {
      agent: true,
      task: true
    }
  });

  if (!draft) {
    throw notFound("Draft");
  }

  if (draft.platform === "internal") {
    throw new AppError(400, "Internal drafts cannot be regenerated by social agents");
  }

  const brandProfile = await getDefaultBrandProfile();
  const revisionPrompt = [
    draft.task?.prompt ?? `Rigenera questa bozza ${draft.platform}.`,
    "",
    "Previous draft:",
    draft.content,
    "",
    params.comment ? `User feedback: ${params.comment}` : "User feedback: improve specificity and brand fit."
  ].join("\n");
  const agentContext = {
    ...(draft.taskId ? { taskId: draft.taskId } : {}),
    agentSlug: draft.agent.slug,
    draftId: draft.id
  };
  const supervisorContext = {
    ...(draft.taskId ? { taskId: draft.taskId } : {}),
    agentSlug: "overseer",
    draftId: draft.id
  };

  const generated =
    draft.agent.slug === "instaspark"
      ? await runInstagramAgent(revisionPrompt, brandProfile, agentContext)
      : await runLinkedInAgent(revisionPrompt, brandProfile, agentContext);

  const review = await reviewDraftWithSupervisor({
    title: generated.title,
    content: generated.content,
    platform: draft.platform,
    brandProfile,
    userFeedback: params.comment,
    context: supervisorContext
  });

  const nextVersion = await createDraftVersion({
    draft,
    title: generated.title,
    content: generated.content,
    review,
    createdBy: params.action === "regenerate" ? "regenerate" : "revision",
    ...(params.comment ? { userFeedback: params.comment } : {})
  });

  const updated = await db.$transaction(async (tx: any) => {
    const savedDraft = await tx.draft.update({
      where: { id: draft.id },
      data: {
        title: generated.title,
        content: generated.content,
        status: "waiting_approval",
        supervisorScore: review.qualityScore,
        riskLevel: review.riskLevel,
        supervisorFeedback: review.feedback,
        recommendedAction: review.recommendedAction,
        currentVersion: nextVersion
      }
    });

    await tx.approval.create({
      data: {
        draftId: draft.id,
        userId: params.userId,
        action: params.action === "regenerate" ? "edit" : "request_revision",
        previousStatus: draft.status,
        newStatus: "waiting_approval",
        comment: params.comment ?? null
      }
    });

    if (draft.taskId) {
      await tx.task.update({
        where: { id: draft.taskId },
        data: {
          status: "waiting_approval",
          result: generated.content,
          resultJson: {
            draftId: draft.id,
            version: nextVersion,
            generated,
            supervisorReview: review
          }
        }
      });

      await tx.taskEvent.create({
        data: {
          taskId: draft.taskId,
          type: "draft.regenerated",
          message: "Draft regenerated after review feedback",
          meta: { draftId: draft.id, version: nextVersion, action: params.action }
        }
      });
    }

    await tx.agent.update({
      where: { id: draft.agentId },
      data: { status: "waiting_approval" }
    });

    await tx.agentLog.create({
      data: {
        agentId: draft.agentId,
        message: "Draft regenerated",
        meta: { draftId: draft.id, version: nextVersion, action: params.action }
      }
    });

    return savedDraft;
  });

  await createNotification({
    type: "draft.regenerated",
    title: "Nuova versione bozza pronta",
    message: `${draft.agent.name} ha creato la versione ${nextVersion}.`,
    meta: {
      draftId: draft.id,
      taskId: draft.taskId,
      version: nextVersion,
      recommendedAction: review.recommendedAction
    }
  });

  await notifyTelegramDraftReady(draft.id).catch((error) => {
    console.warn("telegram.draft_notification_failed", {
      draftId: draft.id,
      message: error instanceof Error ? error.message : "unknown"
    });
  });

  if (review.recommendedAction === "revise" || review.recommendedAction === "reject") {
    await createNotification({
      type: `supervisor.${review.recommendedAction}`,
      title: "Supervisor richiede attenzione",
      message: `Overseer consiglia: ${review.recommendedAction}.`,
      meta: {
        draftId: draft.id,
        taskId: draft.taskId,
        version: nextVersion,
        riskLevel: review.riskLevel,
        qualityScore: review.qualityScore
      }
    });
  }

  return {
    draft: updated,
    supervisorReview: review
  };
}
